apiVersion: v1
kind: Service
metadata:
  name: avfomichev-test-app-service
  namespace: test-application
spec:
  type: NodePort
  selector:
    app: avfomichev-web-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30071
